name: CI

on: [push, pull_request]

env:
    CARGO_TERM_COLOR: always

jobs:
    build_linux:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Cargo Format
        run: cargo fmt -- --check
    build_windows:
      runs-on: windows-latest
      steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose      
    build_macos:
      runs-on: macos-latest
      steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
    nightly_features_linux:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose --all-features 
